Add feed
codeByDope/java-filmorate pull request #21
Opened 2024-04-17 17:04 UTC by BlackBox15

Лента событий, отражающая действия пользователя:

1. добавления другого пользователя в друзья (FRIEND.ADD)
2. удаление одного из пользователей из друзей (FRIEND.REMOVE)
3. добавление лайка к фильму (LIKE.ADD)
4. удаление лайка из фильма (LIKE.REMOVE)
5. добавление отзыва (REVIEW.ADD)
6. обновление отзыва (REVIEW.UPDATE)
7. удаление отзыва (REVIEW.REMOVE)

2024-04-17 17:42 UTC, codeByDope requested changes

2024-04-17 17:42 UTC, codeByDope commented on src/main/java/ru/yandex/practicum/filmorate/controller/FeedController.java
> +@RequestMapping("/users")
Мне кажется, надо вынести в `ApiPathConstants`

2024-04-17 17:42 UTC, codeByDope commented on src/main/java/ru/yandex/practicum/filmorate/controller/FeedController.java
> +    @GetMapping("/{id}/feed")
Аналогично пред комменту

2024-04-17 17:42 UTC, codeByDope commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
>          return ResponseEntity.status(200)
Тут у тебя не обновленная версия кода Иры, сделай Update

2024-04-17 17:42 UTC, codeByDope commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FeedRowMapper.java
> +        return null;
Не понял. Почему null? Разве не return feed?

2024-04-17 17:42 UTC, codeByDope commented on src/main/java/ru/yandex/practicum/filmorate/service/feed/FeedService.java
> +    List<Feed> getAllByUserId(Long userId);
На первый взгляд не понял, что должен делать метод. Мне кажется, что стоит переименовать его в `getUserFeedById` или `getFeedByUserId`

2024-04-17 17:42 UTC, codeByDope commented on src/main/java/ru/yandex/practicum/filmorate/service/feed/FeedServiceImpl.java
> +    public Feed addEvent(Long userId, Long entityId, FeedEventType et, FeedOperationType ot) {
Мне кажется, лучше делать полное название переменной, потому что другому разработчику будет тяжеловато читать. Я бы назвал et как eventType, ot - operationType

2024-04-17 17:42 UTC, codeByDope commented on src/main/java/ru/yandex/practicum/filmorate/service/films/FilmServiceImpl.java
> +    @Override    public List<Film> getDirectorFilms(int directorId, String sortBy) {
Что-то тут съехало

2024-04-17 17:42 UTC, codeByDope commented on src/main/java/ru/yandex/practicum/filmorate/service/likers/LikerServiceImpl.java
> +        //todo: событие - в ленту
я так понимаю, что коммент нужен был, чтоб ты не забыл вписать туда код?

2024-04-17 17:42 UTC, codeByDope commented on src/main/java/ru/yandex/practicum/filmorate/service/reviews/ReviewServiceImpl.java
> +        return reviewFromDb;
Можно просто `return reviewStorage.addReview(review);` и убрать переменную reviewFromDb

2024-04-17 17:42 UTC, codeByDope commented on src/main/java/ru/yandex/practicum/filmorate/service/reviews/ReviewServiceImpl.java
> +        return reviewFromDb;
Аналогично

2024-04-17 17:42 UTC, codeByDope commented on src/main/java/ru/yandex/practicum/filmorate/service/reviews/ReviewServiceImpl.java
> +        //todo: проверить работу методов для ленты событий (feedservice)
Если для себя - лучше убрать

2024-04-17 17:42 UTC, codeByDope commented on src/main/resources/schema.sql
> +--DROP TABLE IF EXISTS friends CASCADE;
надо вернуть очистку базу данных

2024-04-17 17:56 UTC, BlackBox15 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FeedController.java
> +@RequestMapping("/users")
сделал

2024-04-17 17:56 UTC, BlackBox15 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FeedController.java
> +    @GetMapping("/{id}/feed")
сделал

2024-04-17 18:23 UTC, BlackBox15 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
>          return ResponseEntity.status(200)
пока непонятно..

2024-04-17 18:23 UTC, BlackBox15 commented on src/main/java/ru/yandex/practicum/filmorate/service/likers/LikerServiceImpl.java
> +        //todo: событие - в ленту
да, забыл убрать todo..

2024-04-17 18:24 UTC, BlackBox15 commented on src/main/java/ru/yandex/practicum/filmorate/service/reviews/ReviewServiceImpl.java
> +        //todo: проверить работу методов для ленты событий (feedservice)
согласен

2024-04-17 18:24 UTC, BlackBox15 commented on src/main/resources/schema.sql
> +--DROP TABLE IF EXISTS friends CASCADE;
принято
использовал такой подход, пока тесты проходил

2024-04-17 18:27 UTC, BlackBox15 commented on src/main/java/ru/yandex/practicum/filmorate/service/reviews/ReviewServiceImpl.java
> +        //todo: проверить работу методов для ленты событий (feedservice)
выполнил

2024-04-17 18:27 UTC, BlackBox15 commented on src/main/java/ru/yandex/practicum/filmorate/service/likers/LikerServiceImpl.java
> +        //todo: событие - в ленту
выполнил

2024-04-17 18:44 UTC, BlackBox15 commented on src/main/java/ru/yandex/practicum/filmorate/service/feed/FeedService.java
> +    List<Feed> getAllByUserId(Long userId);
выполнил
переименовал в getFeedByUserId

2024-04-17 18:57 UTC, BlackBox15 commented on src/main/java/ru/yandex/practicum/filmorate/mapper/FeedRowMapper.java
> +        return null;
согласен
выполнил

..я забыл, что null оставил

2024-04-17 20:16 UTC, RinOrlova commented on src/main/java/ru/yandex/practicum/filmorate/service/films/FilmServiceImpl.java
> +    @Override    public List<Film> getDirectorFilms(int directorId, String sortBy) {
да, похоже, что снес случайно чужой метод, когда решал конфликты...

2024-04-17 20:22 UTC, RinOrlova commented on src/main/java/ru/yandex/practicum/filmorate/storage/feed/FeedDbStorage.java
> +     */
комментарий, наверное, уже не нужен?

2024-04-17 20:23 UTC, RinOrlova commented on src/main/java/ru/yandex/practicum/filmorate/storage/feed/FeedDbStorage.java
> +     */
и тут тоже

2024-04-17 20:28 UTC, BlackBox15 commented on src/main/java/ru/yandex/practicum/filmorate/service/reviews/ReviewServiceImpl.java
> +        return reviewFromDb;
я использовал промежуточную переменную `reviewFromDb`, чтобы добавить запись в таблицу `feed `(лента событий) - там требуется заполнить поля `user_id`, `feed_id`.

`user_id` я могу вытащить из входящего аргумента - `review`,
`feed_id` присваивается СУБД только после выполнения `addReview(review)`.

2024-04-17 20:32 UTC, BlackBox15 commented on src/main/java/ru/yandex/practicum/filmorate/storage/feed/FeedDbStorage.java
> +     */
это же javadoc, думал, приучать себя делать описания методов..

2024-04-17 20:33 UTC, BlackBox15 commented on src/main/java/ru/yandex/practicum/filmorate/storage/feed/FeedDbStorage.java
> +     */
javadoc...
если ctrl + alt + q, то будет читабельный вид

2024-04-17 21:27 UTC, RinOrlova approved these changes

2024-04-18 04:59 UTC, codeByDope requested changes

2024-04-18 04:59 UTC, codeByDope commented on src/main/java/ru/yandex/practicum/filmorate/controller/FriendsController.java
> +    @GetMapping("/{id}/friends/common/{otherId}")
аналогично

2024-04-18 05:08 UTC, codeByDope approved these changes

2024-04-18 08:59 UTC, BlackBox15 commented on src/main/java/ru/yandex/practicum/filmorate/controller/LikersController.java
> +    @PutMapping("/{id}/like/{userId}")
исправил

2024-04-18 09:01 UTC, BlackBox15 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @DeleteMapping("/{id}")
выполнил сравнение файла с веткой develop, сейчас различий нет

2024-04-18 09:16 UTC, merged