Develop
codeByDope/java-filmorate pull request #22
Opened 2024-04-18 09:17 UTC by codeByDope

2024-04-18 21:47 UTC, andrew-larkin requested changes
Всем привет! Вы отлично постарались, приложение получилось очень близким по наполнению и технологиям к тому, что в реальности пишут разработчики в Яндексе, Сбере и Авито. Много плюсов - у вас получились отличные запросы к таблицам, хорошо разобрались во взаимодействии между сервисами/контроллерами/репозиториями, архитектура выполнена действительно качественно. Есть всего несколько моментов по коду - вы сможете быстро их поправить. И еще совсем не помешал бы заполненный readme файл, т.к. такому большому проекту очень не хватает описания его функционала. Это все что требуется сделать для того, чтобы проект был полностью готов.

2024-04-18 21:47 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/utils/ApiPathConstants.java
> +public class ApiPathConstants {
классная идея!

2024-04-18 21:47 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @NotNull
по-моему над классом нужно поставить @Validated, чтобы эти аннотации заработали

2024-04-18 21:47 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @NotNull
тут тоже скорее всего потребуется @Validated

2024-04-18 21:47 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/domain/ReviewDO.java
> +@Value
смотрим документацию по аннотации @Value и видим - all fields are made private and final by default, and setters are not generated. dto - это объект, который не обладает финализированными полями, сеттеры тут точно нужны

2024-04-18 21:47 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@Value
а вот директор - элемент модели. для моделей не стоит использовать @Value или @Data, потому что в обоих случаях они некорректно рассчитывают хэш - из-за этого хранить некоторое кол-во экземпляров класса в той же hashMap становится не оптимальным решением. тут стоит использовать аннотации @Getter, @Setter и т.д. - это актуально для всех классов-моделей

2024-04-18 21:47 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/service/films/FilmServiceImpl.java
> +
над переопределенными методами ставим @Override

2024-04-18 21:47 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/feed/FeedDbStorage.java
> +     * Добавление события в ленту событий.
за документацию в классах - отдельный плюс!

2024-04-18 21:47 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    private static final String GET_REVIEW_BY_ID = "SELECT r.*, " +
такой большой запрос с двумя подзапросами - может попробовать разделить его на несколько отдельных запросов?

2024-04-19 09:25 UTC, RinOrlova commented on src/main/java/ru/yandex/practicum/filmorate/domain/ReviewDO.java
> +@Value
Объект ReviewDO создается только через билдер в классе ReviewRowMapper и нигде не модифицируется. Мне кажется, сеттеры тут не нужны. Или я неправильно понимаю?

2024-04-19 09:40 UTC, RinOrlova commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    private static final String GET_REVIEW_BY_ID = "SELECT r.*, " +
Готова попробовать разделить, но аргументирую свою реализацию :)
Сейчас у нас один запрос в базу, если разделить запрос на несколько, как я понимаю, их будет три. Мне казалось, что чем меньше мы ходим в базу, тем лучше, но могу ошибаться.
Кроме того, этот запрос сейчас возвращает все данные, чтобы сделать полноценный ДО и не сетить ничего отдельно. Это позволяет использовать rowMapper-ы без дополнительных параметров.

2024-04-19 10:26 UTC, RinOrlova commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @NotNull
обнаружили, что @NotNull для метода, возвращающего void, не нужен, повесили для @Positiv в c90adc0d180ac2349cafb59b9e5eede8a4639e65

2024-04-19 10:26 UTC, RinOrlova commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @NotNull
обнаружили, что @NotNull для метода, возвращающего void, не нужен, повесили для @Positiv в c90adc0d180ac2349cafb59b9e5eede8a4639e65

2024-04-19 10:27 UTC, RinOrlova commented on src/main/java/ru/yandex/practicum/filmorate/service/films/FilmServiceImpl.java
> +
Исправили в c90adc0d180ac2349cafb59b9e5eede8a4639e65

2024-04-20 17:26 UTC, andrew-larkin requested changes
Всем привет! В моделях один момент с аннотациями пропустили - это поправить и работа будет принята.

2024-04-20 17:26 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    int id;
тут тепер должны быть модификаторы доступа

2024-04-20 17:26 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +public class Feed {
элемент модели. для моделей не стоит использовать @value или @DaTa, потому что в обоих случаях они некорректно рассчитывают хэш - из-за этого хранить некоторое кол-во экземпляров класса в той же hashMap становится не оптимальным решением. тут стоит использовать аннотации @getter, @Setter и т.д. - это актуально для всех классов-моделей

2024-04-20 17:26 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  @Data
элемент модели. для моделей не стоит использовать @value или @DaTa, потому что в обоих случаях они некорректно рассчитывают хэш - из-за этого хранить некоторое кол-во экземпляров класса в той же hashMap становится не оптимальным решением. тут стоит использовать аннотации @getter, @Setter и т.д. - это актуально для всех классов-моделей

2024-04-20 17:26 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +@Value
элемент модели. для моделей не стоит использовать @value или @DaTa, потому что в обоих случаях они некорректно рассчитывают хэш - из-за этого хранить некоторое кол-во экземпляров класса в той же hashMap становится не оптимальным решением. тут стоит использовать аннотации @getter, @Setter и т.д. - это актуально для всех классов-моделей

2024-04-20 17:26 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +    private static final String GET_REVIEW_BY_ID = "SELECT r.*, " +
принимаю)

2024-04-20 20:30 UTC, RinOrlova commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +@Value
поправили в c3bcd273c7d9f113c61b94cdea82a2d1e211029d

2024-04-20 20:31 UTC, RinOrlova commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    int id;
поправили в c3bcd273c7d9f113c61b94cdea82a2d1e211029d

2024-04-20 20:31 UTC, RinOrlova commented on src/main/java/ru/yandex/practicum/filmorate/model/Feed.java
> +public class Feed {
поправили в c3bcd273c7d9f113c61b94cdea82a2d1e211029d

2024-04-20 20:31 UTC, RinOrlova commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  @Data
поправили в c3bcd273c7d9f113c61b94cdea82a2d1e211029d

2024-04-20 20:31 UTC, RinOrlova commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +@Value
поправили в c3bcd273c7d9f113c61b94cdea82a2d1e211029d

2024-04-20 20:45 UTC, andrew-larkin approved these changes
Всем привет! Отлично, все корректировки выполнены, файл readme хорошо написан, приложение полностью готово с чем вас и поздравляю! Командная работа, судя по коммитам, была качественно организована, так что вы получили представление о том, как это все происходит на реальном проекте. Местами могло казаться, что какие-то вещи реализовать сложно или даже невозможно. Но вместе вы со всем этим справились. Помните, что на реальных проектах у вас также будут коллеги, готовые вам помочь, а также не забывайте помогать им. Потому что только благодаря совместным усилиям такие проекты как google, openAI, facebook существуют в нашем мире. И помните, что вы можете стать частью этих крупных проектов, внести в них свою лепту или создать свой собственный продукт, который изменит этот мир. Теперь вы на финишной прямой, желаю всем успешно завершить этот курс и как можно скорее найти свою первую работу!

2024-04-20 21:06 UTC, merged